import Header from '@/components/Header';
import Image from 'next/image';
import ProfilePic from '@/public/ProfilePic.jpg';
import CSS from '@/public/logos/css3.svg';
import HTMl from '@/public/logos/html5.svg';
import JS from '@/public/logos/javascript.svg';
import TS from '@/public/logos/typescript.svg';
import rea from '@/public/logos/react.svg';
import py from '@/public/logos/python.svg';
import rdx from '@/public/logos/redux.svg';
import node from '@/public/logos/nodejs.svg';
import mdb from '@/public/logos/mongodb.svg';
import psql from '@/public/logos/postgresql.svg';
import MyBlogs from '@/components/MyBlogs';

export default function Home() {
  return (
    <section>
      <Header />
      <main className="mx-auto w-full max-w-3xl px-4 pt-4 md:px-12 border-l border-r">
        <h1 className="text-3xl font-bold tracking-tight lg:text-5xl mt-3">
          Hi! I&apos;m{' '}
          <span className="text-[#617bff]">Yashwanth Kothakota</span>
        </h1>
        <div className="mt-10 flex items-center justify-center w-full gap-2">
          <div className="aspect-square w-1/2 overflow-hidden rounded-lg  shadow-lg transform hover:scale-105 transition-transform duration-200">
            <Image
              src={ProfilePic}
              alt="Profile picture"
              width={250}
              height={250}
              className="object-cover object-center w-full h-full rounded-lg"
            />
          </div>
          <div className="w-1/2 text-left p-2">
            <p className="leading-7">
              I am a 2023{' '}
              <span className="text-[#ffe102]">Computer Science</span> Post
              Graduate from <span className="text-[#617bff]">BITS Pilani</span>.
              I love developing software. I am proficient in Python, Javascript,
              Typescript, SQL. Having very strong foundation of CS core like
              Data Structures and Algorithms, Operating Systems, DBMS, Computer
              Networks help me to crack GATE. Willing to learn new technologies.
              Experienced in Agile methodologies and eager to contribute in fast
              paced development team. I am actively looking for Software
              Developer roles.
            </p>
          </div>
        </div>
        <div className="mt-10 border-t-2 p-4">
          <div className="w-full flex items-center justify-center">
            <h2 className="font-semibold text-2xl text-center mt-6 uppercase tracking-widest text-[#617bff] relative custom-curved-underline">
              Work Experience
            </h2>
          </div>
          <p className="leading-7 mt-2">
            I worked as a Software Engineer Intern at Western Digital for 6
            months. I worked as an individual contributor. Developed an
            application in an agile environment right from requirement analysis
            to production and management. This is a Data Analysis application
            which takes input 100s of GBs of log files of data, clean it,
            process it and generate a summary ppt and report. Summary ppt file
            will contain visually stunning plots generated by code and summary
            report contains summary of those plots. This application impacted QA
            team greatly by reducing analyzing time for 500GB of data from
            around 15 days to 45 minutes.
          </p>
          <p className="leading-7 mt-2">
            Backend developed in Python using Pandas and Dataframes, For plots
            matplotlib library is used, Frontend developed in React and
            Javascript with a functionality of notifying QA team after task
            completion, Doxygen tool is used for documentation(HLD, LLD, User
            Manual) and Deployed using Docker.
          </p>
        </div>
        <div className="mt-6 p-6">
          <div className="w-full flex items-center justify-center">
            <h2 className="font-semibold text-2xl text-center uppercase tracking-widest text-[#617bff] relative custom-curved-underline">
              Core Skills
            </h2>
          </div>
          <div className="flex flex-wrap gap-3 items-center justify-center mt-4">
            <Image src={HTMl} alt="CSS" className="h-8 w-8" />
            <Image src={CSS} alt="CSS" className="h-8 w-8" />
            <Image src={JS} alt="CSS" className="h-8 w-8" />
            <Image src={TS} alt="CSS" className="h-8 w-8" />
            <Image src={rea} alt="CSS" className="h-8 w-8" />
            <Image src={rdx} alt="CSS" className="h-8 w-8" />
            <Image src={node} alt="CSS" className="h-8 w-8" />
            <Image src={mdb} alt="CSS" className="h-8 w-8" />
            <Image src={psql} alt="CSS" className="h-8 w-8" />
            <Image src={py} alt="CSS" className="h-8 w-8" />
          </div>
        </div>
        <div className="mt-6 p-6">
          <div className="w-full flex items-center justify-center">
            <h2 className="w-fit font-semibold text-2xl text-center mb-6 uppercase tracking-widest text-[#617bff] relative custom-curved-underline">
              My Blogs
            </h2>
          </div>
          <MyBlogs />
        </div>
      </main>
    </section>
  );
}
