import Header from '@/components/Header';
import Image from 'next/image';
import ProfilePic from '@/public/ProfilePic.jpg';
import CSS from '@/public/logos/css3.svg';
import HTMl from '@/public/logos/html5.svg';
import JS from '@/public/logos/javascript.svg';
import TS from '@/public/logos/typescript.svg';
import rea from '@/public/logos/react.svg';
import py from '@/public/logos/python.svg';
import rdx from '@/public/logos/redux.svg';
import node from '@/public/logos/nodejs.svg';
import mdb from '@/public/logos/mongodb.svg';
import psql from '@/public/logos/postgresql.svg';
import docker from '@/public/logos/docker.svg';
import MyBlogs from '@/components/MyBlogs';
import MyProjects from '@/components/MyProjects';

export default function Home() {
  return (
    <section>
      <Header />
      <main className="mx-auto w-full max-w-3xl px-4 pt-4 md:px-12">
        <h1 className="text-xl font-bold tracking-tight mt-3">
          Hi! I&apos;m{' '}
          <span className="text-[#617bff]">Yashwanth Kothakota 👋</span>
        </h1>
        <div className="mt-10 flex items-center justify-center w-full gap-2">
          <div className="aspect-square w-1/2 overflow-hidden rounded-lg  shadow-lg transform hover:scale-105 transition-transform duration-200">
            <Image
              src={ProfilePic}
              alt="Profile picture"
              width={250}
              height={250}
              className="object-cover object-center w-full h-full rounded-lg"
            />
          </div>
          <div className="w-1/2 text-left p-2">
            <p className="leading-7 text-justify">
              I am a <span className="text-[#ff0878]">2023</span>{' '}
              <span className="text-[#ffe102]">Computer Science</span> Post
              Graduate from <span className="text-[#617bff]">BITS Pilani</span>.
              I love developing software. I am proficient in{' '}
              <span className="text-[#617bff]">Python</span>,{' '}
              <span className="text-[#617bff]">Javascript</span>,{' '}
              <span className="text-[#617bff]">Typescript</span>,{' '}
              <span className="text-[#617bff]">SQL</span>. Having very good
              foundation of CS core like Data Structures and Algorithms,
              Operating Systems, DBMS, Computer Networks help me to crack{' '}
              <span className="text-[#617bff]">GATE</span>. Willing to learn new
              technologies. Experienced in Agile methodologies and eager to
              contribute in fast paced development team. I am actively looking
              for Software Developer roles.
            </p>
          </div>
        </div>
        <div className="mt-10 border-t-2 p-4">
          <div className="w-full flex items-center justify-center">
            <h2 className="font-semibold text-2xl text-center mt-6 uppercase tracking-widest text-[#617bff] relative custom-curved-underline">
              Work Experience
            </h2>
          </div>
          <p className="leading-7 mt-2 text-justify">
            I worked as a{' '}
            <span className="text-[#ff0878]">Software Engineer Intern</span> at{' '}
            <span className="text-[#617bff]">Western Digital</span> for 6
            months. I worked as an{' '}
            <span className="text-[#617bff]">individual contributor</span>.
            Developed an application in an agile environment right from
            requirement analysis to production and management. This is a{' '}
            <span className="text-[#ff0878]">Data Analysis</span> application
            which takes input{' '}
            <span className="text-[#617bff]">100s of GBs of log files</span> of
            data, clean it, process it and generates a{' '}
            <span className="text-[#ff0878]">summary ppt with report</span>.
            Summary ppt file will contain visually stunning plots generated by
            code and summary report contains summary of those plots. This
            application impacted QA team greatly by{' '}
            <span className="text-[#ffe102]">
              reducing analyzing time for 500GB of data from around 10-15 days
              to 45 minutes
            </span>
            .
          </p>
          <p className="leading-7 mt-2 text-justify">
            Backend developed in <span className="text-[#ff0878]">Python</span>{' '}
            using Pandas and Dataframes, For plots{' '}
            <span className="text-[#ff0878]">matplotlib</span> library is used,
            Frontend developed in{' '}
            <span className="text-[#ff0878]">React and Javascript</span> with a
            functionality of notifying QA team after task completion,{' '}
            <span className="text-[#ff0878]">Doxygen</span>
            tool is used for documentation(HLD, LLD, User Manual) and Deployed
            using <span className="text-[#ff0878]">Docker</span>.
          </p>
        </div>
        <div className="mt-6 p-6">
          <div className="w-full flex items-center justify-center">
            <h2 className="font-semibold text-2xl text-center uppercase tracking-widest text-[#617bff] relative custom-curved-underline">
              Core Skills
            </h2>
          </div>
          <div className="flex flex-wrap gap-3 items-center justify-center mt-4">
            <Image src={HTMl} alt="CSS" className="h-8 w-8" />
            <Image src={CSS} alt="CSS" className="h-8 w-8" />
            <Image src={JS} alt="Javascript" className="h-8 w-8" />
            <Image src={TS} alt="Typescript" className="h-8 w-8" />
            <Image src={rea} alt="React" className="h-8 w-8" />
            <Image src={rdx} alt="Redux" className="h-8 w-8" />
            <Image src={node} alt="Node.js" className="h-8 w-8" />
            <Image src={mdb} alt="MongoDB" className="h-8 w-8" />
            <Image src={psql} alt="PostgreSQL" className="h-8 w-8" />
            <Image src={py} alt="Python" className="h-8 w-8" />
            <Image src={docker} alt="Docker" className="h-8 w-8" />
          </div>
        </div>
        <div className="mt-6 p-6">
          <div className="w-full flex items-center justify-center">
            <h2 className="w-fit font-semibold text-2xl text-center mb-6 uppercase tracking-widest text-[#617bff] relative custom-curved-underline">
              My Projects
            </h2>
          </div>
          <MyProjects />
        </div>
        <div className="mt-6 p-6">
          <div className="w-full flex items-center justify-center">
            <h2 className="w-fit font-semibold text-2xl text-center mb-6 uppercase tracking-widest text-[#617bff] relative custom-curved-underline">
              My Blogs
            </h2>
          </div>
          <MyBlogs />
        </div>
      </main>
    </section>
  );
}
